
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deltaAqua"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "aws-opentelemetry-distro >= 0.10.0",
    "bedrock-agentcore >= 1.0.3",
    "boto3 >= 1.42.30",
    "composio-langchain >= 0.10.7",
    "google-auth >= 2.25.0",
    "google-genai >= 1.57.0",
    "httpx >= 0.28.1",
    "langchain>=1.0.3",
    "langchain-google-genai >= 3.0.3",
    "langchain-mcp-adapters>=0.1.11",
    "langgraph>=1.0.2",
    "mcp >= 1.19.0",
    "pinecone >= 8.0.0",
    "pydantic-settings >= 2.12.0",
    "python-dotenv >= 1.2.1",
    "pytest >= 7.0.0",
    "pytest-asyncio >= 0.21.0",
    "tiktoken==0.11.0",
    "composio-langgraph>=0.10.10",
    "langchain-openai>=1.1.7",
    "instructor>=1.14.5",
    "pydantic>=2.12.5",
    "langgraph-checkpoint-aws>=1.0.4",
    "langchain-aws>=1.2.5",
    "langchain-core>=1.2.17",
]
